[haproxy]

[swarm_managers]
10.20.10.5
10.20.10.6
10.20.10.7

[swarm_workers]
10.20.10.8
10.20.10.9
10.20.10.10
10.20.10.11
10.20.10.12
10.20.10.13
10.20.10.14
10.20.10.15
10.20.10.16

[swarm_nodes:children]
swarm_managers
swarm_workers

[gluster_nodes]
10.20.10.6
10.20.10.7
10.20.10.5

[gluster_nodes_bricks]
10.20.10.6
10.20.10.7
10.20.10.5

[traefik]
10.20.10.5
10.20.10.6
10.20.10.7

[all:vars]

docker_version=29.3.0
# Domain used in docker swarm nodes
app_domain_name=localdomain
## Способ хранения данных
# Если false — роль `gluster` НЕ будет монтировать отдельный /dev/sdb и форматировать в XFS (пропустит xfs.yml). 
# Если true, то будет использован отдельный /dev/sdb и форматирован в XFS для хранения данных.
gluster_use_xfs_device=false
# Если gluster_use_xfs_device: true, то bricks использует отдельный /dev/sdb и форматирован в XFS для хранения данных.
gluster_volume_path=/glusterfs/bricks
# Имя тома для GlusterFS
gluster_volume_name=gfs
# Путь монтирования
gluster_mount_path=/mnt/gfs
# Устройство для хранения данных
device2_hdd_dev="/dev/sdb"

# Keepalived VIP for HAProxy
keepalived_vip_cidr=10.20.10.253/24

ansible_connection="ssh"
# user for ansible
#ansible_user="debian"
# mkpasswd --method=SHA-512
# debian
#ansible_ssh_pass="$y$j9T$6faFjvbPr5Ocoh/RFRCPC0$CYwlCnc/GmkSPcA1nmuA3rT3fX5w5Y5zxzy6OmVO2R0"
ansible_user="root"
# root
#ansible_become_pass="$y$j9T$BwSqH9SO3u6QoSRhShQat0$S880K.HmHJtAJUfdFdt7iaUxadTtsagWwo/PbqD8XO."
# rsa public file
ansible_ssh_rsa="~/.ssh/id_ed25519.pub"
# cat ~/.ssh/id_rsa.pub
ansible_ssh_key="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL5yX4w/4ydrZBoSpp6XWUq+TnbZODB3lFwAy4an6tnJ aSSa@MS-7D48"
