[haproxy]

[swarm_managers]

[swarm_workers]

[gluster_nodes]
176.99.153.246
176.99.153.247
176.99.153.248

[traefik]

[all:vars]
#
device2_hdd_dev="/dev/sdb"
#
ansible_connection="ssh"
# user for ansible
#ansible_user="debian"
# mkpasswd --method=SHA-512
# debian
#ansible_ssh_pass="$y$j9T$6faFjvbPr5Ocoh/RFRCPC0$CYwlCnc/GmkSPcA1nmuA3rT3fX5w5Y5zxzy6OmVO2R0"
ansible_user="root"
# root
#ansible_become_pass="$y$j9T$BwSqH9SO3u6QoSRhShQat0$S880K.HmHJtAJUfdFdt7iaUxadTtsagWwo/PbqD8XO."
# rsa public file
ansible_ssh_rsa="~/.ssh/id_ed25519.pub"
# cat ~/.ssh/id_rsa.pub
ansible_ssh_key="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL5yX4w/4ydrZBoSpp6XWUq+TnbZODB3lFwAy4an6tnJ aSSa@MS-7D48"
