---
target_docker_version: 26.1.5
docker_packages:
  - docker-ce
  - containerd.io
#  - docker-ce-cli
#  - docker-buildx-plugin
#  - docker-compose-plugin
old_docker_packages:
  - docker
  - docker-engine
  - docker.io
  - docker-cli
  - containerd.io
  - containerd
  - runc
app_domain_name: localdomain 
gluster_volume_path: /glusterfs/bricks
gluster_volume_name: gfs
gluster_mount_path: /mnt/gfs
portainer_admin_port: 9000
portainer_tunnel_port: 8000
portainer_gfs_subdir: portainer_gfs
portainer_network_name: portainer_network
portainer_volume_name: portainer_data
portainer_app_name: portainer_app
portainer_admin_user: admin
portainer_admin_password: portainer1234
portainer_agent_secret: portaineragenttocken
traefik_listen_port: 80
traefik_admin_port: 8080
traefik_network_name: traefik_network
traefik_app_name: traefik_app
traefik_admin_user: traefik_admin
traefik_admin_password: traefik1234
haproxy_stats_user: haproxy_stats
haproxy_stats_password: haproxy1234

