---
- name: Remove old versions of Docker
  become: true
  become_method: sudo
  apt:
    state: absent
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    force_apt_get: true

- name: Add Docker GPG apt Key
  become: true
  become_method: sudo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  become_method: sudo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present

- name: Install Docker
  become: true
  become_method: sudo
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    force_apt_get: true
    update_cache: yes

- name: Install Docker Python library
  become: true
  become_method: sudo
  pip:
    name: docker

- name: Add "{{ansible_user}}" user to "docker" group
  become: true
  become_method: sudo
  shell: "adduser {{ansible_user}} docker"

- name: Waiting for Docker service to become available
  wait_for:
    path: /var/run/docker.sock

