---
# Дубли при отсутствии ключей в роли cluster-defaults (playbooks/roles/cluster-defaults/defaults/main.yml).
traefik_http_port: 8080
traefik_https_port: 8443
traefik_admin_port: 8090
traefik_internal_api_port: 9081
