version: "3.8"

services:
  frontend-minio:
    image: minio/minio:latest
    command: server /data --console-address ":9005"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.betradar.vpn != yes
        preferences:
          - spread: node.role
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        order: stop-first
        failure_action: rollback
    environment:
      - TZ=Europe/Moscow
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - "${MINIO_API_PORT:-}:9000"
      - "${MINIO_WEBUI_PORT:-}:9005"
    networks:
      - frontend-network
    volumes:
      - minio-data:/data

volumes:
  minio-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/gfs/frontend-minio/data

networks:
  frontend-network:
    external: true

