---
portainer_admin_port: 9090
portainer_tunnel_port: 8000
portainer_gfs_subdir: portainer_gfs
portainer_network_name: portainer_network
portainer_volume_name: portainer_data
portainer_app_name: portainer_app
portainer_admin_user: admin
portainer_admin_password: portainer1234
portainer_agent_secret: portaineragenttocken
