{
 "title": "Bethome Release Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Пользователи онлайн",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bethome_server_users_online)",
     "legendFormat": "online"
    }
   ]
  },
  {
   "title": "Раббит сообщения",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bethome_betradaramqp_amqp_per_minute",
     "legendFormat": "Событий"
    }
   ]
  },
  {
   "title": "Таблици в кеше (_en/_ru)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bethome_cachetable_table_cache",
     "legendFormat": "{{status}}_{{lang}}{{language}}"
    }
   ]
  },
  {
   "title": "HTTP запросы к бетрадару",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bethome_betradarhttp_http_per_minute",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Бетов в кеше",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "bethome_cachebet_cache_bet_count",
     "legendFormat": "{{cache}}"
    }
   ]
  }
 ]
}