---
- name: Label Swarm nodes that have GFS mount (by node ID, not hostname)
  when: inventory_hostname == groups['swarm_managers'][0]
  run_once: true
  vars:
    gfs_nodes: "{{ (groups['swarm_managers'] | default([])) + (groups['swarm_workers'] | default([])) }}"
  include_tasks: label-one-node.yml
  loop: "{{ gfs_nodes | unique }}"
  loop_control:
    loop_var: gfs_target_host
