---
- name: Copy root-ca.crt on the remote machine
  become: true
  become_method: sudo
  copy:
    src: "{{ playbook_dir }}/roles/generate-certs/files/root-ca.crt"
    dest: "${HOME}/root-ca.crt"

- name: Copy root-ca.crt to /usr/share/ca-certificates/root-ca.crt
  become: true
  become_method: sudo
  copy:
    src: "{{ playbook_dir }}/roles/generate-certs/files/root-ca.crt"
    dest: "/usr/share/ca-certificates/root-ca.crt"

- name: Copy root-ca.key on the remote machine
  become: true
  become_method: sudo
  copy:
    src: "{{ playbook_dir }}/roles/generate-certs/files/root-ca.key"
    dest: "${HOME}/root-ca.key"

- name: update trusted ca debian/ubuntu
  become: true
  become_method: sudo
  shell: /usr/sbin/update-ca-certificates

- name: Copy {{ app_domain_name }}.crt on the remote machine
  become: true
  become_method: sudo
  copy:
    src: "{{ playbook_dir }}/roles/generate-certs/files/{{ app_domain_name }}.crt"
    dest: "${HOME}/{{ app_domain_name }}.crt"

- name: Copy {{ app_domain_name }}.key on the remote machine
  become: true
  become_method: sudo
  copy:
    src: "{{ playbook_dir }}/roles/generate-certs/files/{{ app_domain_name }}.key"
    dest: "${HOME}/{{ app_domain_name }}.key"

- name: Copy cert generation script to host
  become: true
  become_method: sudo
  template:
    src: generate_certs.j2
    dest: /tmp/generate_certs.sh
    mode: '0755'

- name: Run cert generation script
  become: true
  become_method: sudo
  shell: /tmp/generate_certs.sh
