version: "3.8"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      TZ: Europe/Moscow
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
      MINIO_BROWSER_REDIRECT_URL: "http://minio-console.${APP_DOMAIN_NAME:-localdomain}"
      MINIO_SERVER_URL: "http://minio.${APP_DOMAIN_NAME:-localdomain}"
    volumes:
      - minio_data:/data
    networks:
      - traefik_network
    secrets:
      - minio_root_user
      - minio_root_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gfs == true
      labels:
        - "traefik.enable=true"

        # S3 API (port 9000)
        - "traefik.http.routers.minio.rule=Host(`minio.${APP_DOMAIN_NAME:-localdomain}`)"
        - "traefik.http.routers.minio.entrypoints=web"
        - "traefik.http.services.minio.loadbalancer.server.port=9000"

        # Console UI (port 9001)
        - "traefik.http.routers.minio-console.rule=Host(`minio-console.${APP_DOMAIN_NAME:-localdomain}`)"
        - "traefik.http.routers.minio-console.entrypoints=web"
        - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/gfs/minio-data

networks:
  traefik_network:
    external: true
    name: traefik_network

secrets:
  minio_root_user:
    external: true
  minio_root_password:
    external: true
