apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: Bethome Prometheus
    uid: bethome_prometheus
    type: prometheus
    access: proxy
    url: http://bethome-infra_prometheus:9090
    isDefault: false
    editable: true
