---
# ansible-playbook -i inventory-prod.ini playbooks/plays/03-firewall-iptables.yml
- hosts: swarm_managers:swarm_workers:gluster_nodes:haproxy
  tags: [firewall-iptables]
  roles:
    - role: ../roles/cluster-defaults
  tasks:
    - import_role:
        name: ../roles/firewall-iptables
      tags: [firewall-iptables]
