---
# ansible-playbook -i inventory-prod.ini playbooks/plays/05-docker-swarm-workers.yml
- hosts: swarm_workers
  tags: [docker, swarm-workers]
  roles:
    - role: ../roles/cluster-defaults
  tasks:
    - import_role:
        name: ../roles/docker
      tags: [docker]
    - import_role:
        name: ../roles/swarm-workers
      tags: [swarm-workers]
