---
# ansible-playbook -i inventory-prod.ini playbooks/plays/05-gluster.yml
- hosts: gluster_nodes
  tags: [gluster]
  roles:
    - role: ../roles/cluster-defaults
  tasks:
    - import_role:
        name: ../roles/gluster
      tags: [gluster]
