---
# ansible-playbook -i inventory-prod.ini playbooks/plays/08-gluster-client.yml
- hosts: swarm_managers:swarm_workers:haproxy:traefik
  tags: [gluster-client]
  roles:
    - role: ../roles/cluster-defaults
  tasks:
    - import_role:
        name: ../roles/gluster-client
      tags: [gluster-client]
