---
# ansible-playbook -i inventory-prod.ini playbooks/plays/10-portainer.yml
- hosts: swarm_managers
  tags: [portainer]
  roles:
    - role: ../roles/cluster-defaults
  tasks:
    - import_role:
        name: ../roles/portainer
      tags: [portainer]
