---
# ansible-playbook -i inventory-prod.ini playbooks/plays/11-haproxy.yml
# HAProxy should start before cert-manager and Traefik.
- hosts: haproxy
  tags: [haproxy]
  roles:
    - role: ../roles/cluster-defaults
  tasks:
    - import_role:
        name: ../roles/haproxy
      tags: [haproxy]
      when: haproxy_enabled | default(true) | bool
