---
# ansible-playbook -i inventory-prod.ini playbooks/plays/13-traefik.yml
- hosts: swarm_managers:traefik
  tags: [traefik]
  roles:
    - role: ../roles/cluster-defaults
  tasks:
    - import_role:
        name: ../roles/traefik
      tags: [traefik]
