---
- name: Check if Swarm has already been initialized
  become: true
  become_method: sudo
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Add Docker node to existing Swarm as manager
  become: true
  become_method: sudo
  vars:
    swarm_manager_first: "{{ (groups['swarm_managers'] | default([])) | first | default('') }}"
  shell: >-
    docker swarm join
    --token {{ hostvars[swarm_manager_first]['manager_token']['stdout'] }}
    {{ swarm_manager_first }}:2377
  when:
    - swarm_status.rc != 0
    - swarm_manager_first | length > 0
    - inventory_hostname != swarm_manager_first
