---
- hosts: swarm_managers
  roles:
    - cluster-defaults
  tasks:
    - import_role:
        name: upgrade-docker

- hosts: swarm_workers
  roles:
    - cluster-defaults
  tasks:
    - import_role:
        name: upgrade-docker
